[gcp_service_account]
project_id = "mss-data-engineer-sandbox"
private_key_id = "f301697db532c16b549026a2de0fa650c5e8a8e4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDEBAQKGaJ4s95C
s/E/OvUSjVD5USB0k9jC7MHVxidEGDp0ccO5B8mB3/pjrVF80LiuBz3RAaYDHaN9
AOVlcCp/QNU0R84hTFxp/6TiywNF6aPjjzcD9KJt4ALFVl9aVT5hre/V11utjGag
tUnf6n6FPA4+lbPKwm17TRaf+qyTENZtlZxgU2lRVpe7oO4wl4EkqLkkI5ltbA8x
iFaixx9hWTWkVgzUKaZCFZb6cZjaKBVoFNE2Le5PZN0CDuaHgj58NoJy4P9aCv6q
UFPfGxBnHx9B27DOKTHzKthiIYGCEQkkhYfIDhc9IA9D1ftIl0iRGuYNy11+BQFt
D30He6UfAgMBAAECggEAMBeqJA5BEitTc3sxzCk7eudIQDt64o9pxf2P21LoTGlD
YlGNS2cRNjfNd8pM7XpKbYxiStcEM8yAUcm3/sjj7F/sT4z0kq/pFqq9+lUEAxG9
f7YiMerCNYIaO++iqoeyrAWgjA9wM2b4wSJpszIWA7uF5S4WtD863F9AF1VKJTS0
uBcPI8NzkqJTyYWFtmSIObRZpRH81VTm4S3knS4WsNtN77KjTOZkA6+MQdARq1KA
9MWRvU/BOSsPrzTUV1GyLItuw8MefJnX0SPrLTx5SYX5ePNkeJe1qrxCWPeTZfmN
WXUviUEDbGh+0VX6Do4skQ0/HU6RDo+19Yir7HIYtQKBgQDvB+ta1cAyhMKWqhBH
Qu7HUFpDYCWt9/aMIJ6GK49XMq0oyeAnwj6vwfzcknQSmph6pHUPrSOchc0pJiAT
ueQLj1UfwDo+XrDT5pMUXQOo07PYfVxM2jX790sqewbBxMTgUMaQK8nY/yrHZ4e7
e90aEw65pHKT9FNqbIouexMiawKBgQDR7ll2N+mOQFEQ54NWpgsC+2gwyiKec8ys
7cN88Yr4fsEVwtUubtAtZwEYMMFsXt/lquYDxKPoZHNZfOSV50Yd38KIrI43PR29
mGYZmyP7UmDG1BYZTt0JcjDoCMdFGZmDkW9UvZqorrH8yc0HbF7PRhzK0Mo5zVA9
wOoojSf9HQKBgQDfHx5TaQmCXqihKNgPHOx0wo2vLLWfYcITZXN0PH8N3zEBzQdf
NZN8TnDxmAefQg2pFZBr9Ks0NTWf/oWcxD2ZiM7l13LGu28GLcoHDRgYZJ0RLVuW
JW6U526Tlcll4H4CAYSIGUfONcnB3uM1X9awuy9YnKeTclLXGcAWyS3ARwKBgCjZ
B+9I0dksCpoPci7aACqEYLGdoz7RqXG8kd0t4qyXfVqOnox6Y2dyM3RRiFFd5JL7
veXdzUbaxNcUxiWk6q/FakTNzp5Q9gh+Lt+soEO2s738ZpBmF/xOi9WaX6vCX2yK
T+9dNUq9M0TMv2hCXfBW5CNSnQbCPGrHrshVLwLBAoGBAOjmWD22u53wQNwpVlbo
F3wjZ+eXnaqB32KG9fhuP1NJfVaZ65INBLboBgfTbsNUXqD+tk5pgDPWF+APNMa/
1ZuHqqUsY7ybsX/LVBYlt/gVJmFFRWFy/dOqLJIQ9iu+KSldYlSBdVYc4kkLMYPe
IO3duHMlIwG8BOBMW9ASoGvE
-----END PRIVATE KEY-----"""
client_email = "dataengg-training@mss-data-engineer-sandbox.iam.gserviceaccount.com"
client_id = "116876153342903559080"
token_uri = "https://oauth2.googleapis.com/token"
type = "service_account"
